version: "3.6"
services:
  Gauravsithole-react-portfolio:
    build:
      context: $PWD/../..
      dockerfile: $PWD/Gauravsithole-react-portfolio/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=Gauravsithole.com, www.Gauravsithole.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=Gauravsithole.com, www.Gauravsithole.com
      - LETSENCRYPT_EMAIL=Gauravsithole@hotmail.co.za
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - Gauravsithole-react-portfolio
    links:
      - Gauravsithole-react-portfolio

networks:
  default:
    external:
      name: nginx-proxy